- name: Install maven
  apt: 
    name: maven
    state: present

- name: Package
  command: mvn package
  args:
    chdir: /usr/share/app/

- name: Copy war to tomcat
  copy:
    src: /usr/share/app/target/hello-1.0.war
    dest: /var/lib/tomcat8/webapps
    remote_src: yes
  notify: 
    - restart TOMCAT
